#!/usr/bin/env zsh

if [[ -z "$JUST_PHOTOS_API_KEY" ]]; then
  echo "JUST_PHOTOS_API_KEY must be set"
  exit 1
fi

API_KEY=$JUST_PHOTOS_API_KEY

DOMAIN=${JUST_PHOTOS_DOMAIN:-"https://justphotos.pages.dev"}

USERNAME="ben"
PREFIX="/r2/"
TMP_DIR="/tmp/justphotos"

mkdir -p $TMP_DIR

function resize {
    EXTENSION="${3:-avif}"
    OUTPUT="$HASH-$2.$EXTENSION"
    TMP_FILE="$TMP_DIR/$OUTPUT"
    magick $1 -auto-orient -resize $2% $TMP_FILE
    WIDTH=$(identify -format "%w" $TMP_FILE)

    upload "$USERNAME/$EXTENSION/$OUTPUT" "$TMP_FILE"

    echo "$USERNAME/$EXTENSION/$OUTPUT ${WIDTH}w"
}

function upload {
    KEY="$1"
    MEDIA="$2"
    EXTRAS="$3"
    CMD="curl -s -X POST -H \"X-Api-Key: ${API_KEY}\" -F \"media=@$MEDIA\" -F \"key=$KEY\" $EXTRAS \"$DOMAIN/r2/upload\""
    eval $CMD > /dev/null
}

function process {
    HASH=$(shasum $INPUT | cut -d ' ' -f 1)
    RESIZE_10=$(resize $INPUT 10)
    RESIZE_25=$(resize $INPUT 25)
    RESIZE_50=$(resize $INPUT 50)
    RESIZE_100=$(resize $INPUT 100)
    SRCSET="$PREFIX$RESIZE_10, $PREFIX$RESIZE_25, $PREFIX$RESIZE_50, $PREFIX$RESIZE_100"

    TMP_FILE="$TMP_DIR/$HASH.jpg"
    cp $INPUT $TMP_FILE
    upload "$USERNAME/original/$HASH" "$TMP_FILE" "-F srcset=\"$SRCSET\""

    echo "$DOMAIN/from/$USERNAME/$HASH"
}


if [[ $# -lt 1 ]]; then
  echo "./justphotos ...photos"
  exit 2
fi

for INPUT in "$@"; do
  if [ -f "$INPUT" ]; then
    process "$INPUT"
  else
    echo "File not found: $INPUT"
  fi
done

rm -rf $TMP_DIR
