name = "justphotos"
pages_build_output_dir = "./dist"

compatibility_date = "2024-08-23"
compatibility_flags = ["streams_enable_constructors"]

[[r2_buckets]]
binding = "R2"
bucket_name = "justphotos"
